export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const REGISTER_VERIFICATION = 'REGISTER_VERIFICATION'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const LOG_OUT = 'LOG_OUT'
export const LOAD_USER =' LOAD_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const LOGOUT = 'LOGOUT'

export const CLEAR_ERROR = 'CLEAR_ERROR'
export const ERROR = 'ERROR'
export const EDIT_FORM = 'EDIT_FORM'
export const CLEAR_EDIT_FORM = 'CLEAR_EDIT_FORM'

export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'



export const GET_PRODUCT= 'GET_PRODUCT'
export const UPLOAD_PRODUCT= 'UPLOAD_PRODUCT'
export const UPDATE_PRODUCT= 'UPDATE_PRODUCT'
export const DELETE_PRODUCT= 'DELETE_PRODUCT'
