
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const REGISTER_VERIFICATION = 'REGISTER_VERIFICATION'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const LOG_OUT = 'LOG_OUT'
export const LOAD_USER =' LOAD_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const LOGOUT = 'LOGOUT'

// export const SEND_FORGET_REQUEST = 'SEND_FORGET_REQUEST'
// export const RESET_REQUEST = 'RESET_REQUEST'
